# Generated by Django 4.2.2 on 2025-04-26 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('w', 'White'), ('b', 'Black'), ('=', 'Draw'), ('+', 'Forfeit win'), ('-', 'Forfeit loss'), ('H', 'Half point bye'), ('F', 'Full point bye'), ('U', 'Unpaired game point bye'), ('Z', 'Zero point bye'), ('*', 'No available')], default='*', max_length=1)),
                ('rankingOrder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('lichess_username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('lichess_rating_bullet', models.IntegerField(default=0)),
                ('lichess_rating_blitz', models.IntegerField(default=0)),
                ('lichess_rating_rapid', models.IntegerField(default=0)),
                ('lichess_rating_classical', models.IntegerField(default=0)),
                ('fide_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('fide_rating_blitz', models.IntegerField(default=0)),
                ('fide_rating_rapid', models.IntegerField(default=0)),
                ('fide_rating_classical', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingSystemClass',
            fields=[
                ('value', models.CharField(choices=[('BU', 'Buchholz'), ('BC', 'Buchholz Cut 1'), ('BA', 'Buchholz Average'), ('SB', 'Sonneborn-Berger'), ('PS', 'Plain Score'), ('WI', 'No. Wins'), ('BT', 'No. games played with Black')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre del árbitro')),
                ('refereeNumber', models.CharField(default='-1', max_length=32, verbose_name='Número de árbitro')),
            ],
            options={
                'verbose_name': 'Árbitro',
                'verbose_name_plural': 'Árbitros',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_update_time', models.IntegerField(default=43200)),
                ('only_administrative', models.BooleanField(default=False)),
                ('tournament_type', models.CharField(choices=[('SR', 'Round Robin Simple'), ('DR', 'Round Robin Doble'), ('DD', 'Round Robin Doble (mismo día)'), ('SW', 'Sistema Suizo')], default='SR', max_length=2)),
                ('tournament_speed', models.CharField(choices=[('BU', 'Bullet'), ('BL', 'Blitz'), ('RA', 'Rápido'), ('CL', 'Clásico')], default='CL', max_length=2)),
                ('board_type', models.CharField(choices=[('LIC', 'lichess'), ('OTB', 'over the board')], default='LIC', max_length=3)),
                ('win_points', models.FloatField(default=1.0)),
                ('draw_points', models.FloatField(default=0.5)),
                ('lose_points', models.FloatField(default=0.0)),
                ('timeControl', models.CharField(default='15+0', max_length=32)),
                ('number_of_rounds_for_swiss', models.IntegerField(default=0)),
                ('administrativeUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, to='chess_models.player')),
                ('rankingList', models.ManyToManyField(blank=True, to='chess_models.rankingsystemclass')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_models.referee')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('finish', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referee',
            constraint=models.UniqueConstraint(fields=('refereeNumber',), name='unique_referee_number'),
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='chess_models.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.round'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='chess_models.player'),
        ),
    ]
